name = "Enigmistics"
uuid = "60f105a3-a574-40c2-bc2c-c04e07a3e561"
authors = ["federico.mor "]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Logging = "1.11.0"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Test = "1.11.0"
